cc_binary(
    name = "ws_stream_client",
    srcs = ["ws_stream_client.cc"],
    copts = ["-std=c++17"],
    deps = [
        "@com_github_grpc_grpc//:grpc++",
        "@opencv//:core",
        "@opencv//:highgui",
        "@opencv//:imgcodecs",
        "@opencv//:imgproc",
    ],
)
